// File generated by FlutterFire CLI.
// ignore_for_file: type=lint
import 'package:firebase_core/firebase_core.dart' show FirebaseOptions;
import 'package:flutter/foundation.dart'
    show defaultTargetPlatform, kIsWeb, TargetPlatform;

/// Default [FirebaseOptions] for use with your Firebase apps.
///
/// Example:
/// ```dart
/// import 'firebase_options.dart';
/// // ...
/// await Firebase.initializeApp(
///   options: DefaultFirebaseOptions.currentPlatform,
/// );
/// ```
class DefaultFirebaseOptions {
  static FirebaseOptions get currentPlatform {
    if (kIsWeb) {
      return web;
    }
    switch (defaultTargetPlatform) {
      case TargetPlatform.android:
        return android;
      case TargetPlatform.iOS:
        return ios;
      default:
        return web;
    }
  }

  static const FirebaseOptions web = FirebaseOptions(
    apiKey: 'AIzaSyDYKXoj-jSeZ0T2Rs1CeIUTfRanU6v4wvs',
    appId: '1:779781321483:web:b3f43f29f8bdc594c8680e',
    messagingSenderId: '779781321483',
    projectId: 'propconnect-b89bd',
    authDomain: 'propconnect-b89bd.firebaseapp.com',
    storageBucket: 'propconnect-b89bd.firebasestorage.app',
    measurementId: 'G-FQLW71GFWP',
  );

  static const FirebaseOptions android = FirebaseOptions(
    apiKey: 'AIzaSyDk3pna4_OkPANeG400zxo5soWyyH-xrEM',
    appId: '1:779781321483:android:9ba82678581281aec8680e',
    messagingSenderId: '779781321483',
    projectId: 'propconnect-b89bd',
    storageBucket: 'propconnect-b89bd.firebasestorage.app',
  );

  static const FirebaseOptions ios = FirebaseOptions(
    apiKey: 'AIzaSyATAqLoAr9k5-Ndb83FIGbt0RXSY8zJilw',
    appId: '1:779781321483:ios:dcf5180dd1a99985c8680e',
    messagingSenderId: '779781321483',
    projectId: 'propconnect-b89bd',
    storageBucket: 'propconnect-b89bd.firebasestorage.app',
    iosBundleId: 'com.example.propconnect',
  );
}
